### ISSUE TITLE
Req.params support

### ISSUE THREAD

**Issue by saavi2** [pdupavillon/express-recaptcha#15]
Hello, you did a great job! As a suggestion you could add support to `req.params` method. I think it would be a good improvement.

I've looked at your code and you just need to add the following code at line 54:

`if(req.params && req.params['g-recaptcha-response']) response = req.params['g-recaptcha-response'];`

Best regards, Wesley.

**Comment by pdupavillon** [comment]
Should be good now,
Thanks !
