### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by stevenvg** [pdupavillon/express-recaptcha#19]
Getting this error:

`node_modules/express-recaptcha/typings/express.d.ts:1:33 - error TS2307: Cannot find module '../src/interfaces'.
1 import {RecaptchaResponse} from '../src/interfaces';`

I manually adjust it for now from: 
`import {RecaptchaResponse} from '../src/interfaces';`
to 
`import {RecaptchaResponse} from '../dist/interfaces';`

but every time my node_modules change, it reverts back to its original value.
Is this something on my side? If not, could you guys please update this?

**Comment by igorVladimirovich** [comment]
+1

**Comment by pdupavillon** [comment]
Hi @stevenvg, @igorVladimirovich, 
I'll look at it

**Comment by pdupavillon** [comment]
Hey y'all,
Should be good with the latest version (4.0.3).
Could you confirm this please ?
Thanks !
