### ISSUE TITLE
Recaptcha not showing

### ISSUE THREAD

**Issue by Dizga** [pdupavillon/express-recaptcha#20]
Recaptcha is not showing
It shows when I change the script src in index.js
from
``<script src='//www.google.com/recaptcha/api.js'></script>``
to
``<script src='https://www.google.com/recaptcha/api.js'></script>``

Am I missing something ?

**Comment by pdupavillon** [comment]
Do you still facing that issue @Dizga ?

**Comment by Dizga** [comment]
Hey @pdupavillon, thx for your quick answer and sorry mine was so late..
Looks like I forgot to disable NoScript, I should have double-checked before posting this issue, my bad. This is working pretty well now.
Thank for this great tool !
