### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by sarkiroka** [pdupavillon/express-recaptcha#22]
I use this great lib with multiple language, but this need always create new instance by constructor. I think good idea on render accept some parameters - as options. This mean only one instance need, but by requests other and other language served.

**Comment by pdupavillon** [comment]
Hey @sarkiroka,
The latest release 4.1.0 introduce `renderWith` method that allows you to override the options.
You can check the doc : https://github.com/pdupavillon/express-recaptcha#render---recaptchamiddlewarerenderwith

Best,
Paul
