### ISSUE TITLE
Publishing v3 to npm

### ISSUE THREAD

**Issue by herkyl** [pdupavillon/express-recaptcha#26]
I see that v3 is already implemented. Any plans on submitting it to npm?

**Comment by MateoWartelle** [comment]
Yes, I am waiting upon that also. Thank you for all your work.

**Comment by slinto** [comment]
@pdupavillon what about release?

**Comment by OmanCoding** [comment]
I am also waiting on RecaptchaV3 to be deployed on the NPM package.
Thanks.

**Comment by franck34** [comment]
`
npm install franck34/express-recaptcha
`

just a compiled version of the master branch, temporary, seem's that @pdupavillon leave the universe

**Comment by pdupavillon** [comment]
Hey y’all,
sorry for the late reply, but the latest version 4.1.1 (published on npm) should include the V3.

**Comment by pdupavillon** [comment]
... I see, there was an issue during the publish step in Travis Ci.
I’ll try to fix that ASAP, and I’ll let you know

**Comment by pdupavillon** [comment]
@herkyl , @MateoWartelle, @slinto, @OmanCoding , @franck34 
The latest buil ran successfully (version 4.2.0) let me know if it’s ok for you too.

**Comment by OmanCoding** [comment]
@franck34 @pdupavillon 
Thank you guys

**Comment by slinto** [comment]
thx!

**Comment by franck34** [comment]
thank you paul :D

**Comment by herkyl** [comment]
Thanks @pdupavillon !!
