### ISSUE TITLE
ejs v3 display problem

### ISSUE THREAD

**Issue by vahid263** [pdupavillon/express-recaptcha#29]
I recently update express-recaptcha to last version and update my code but my problem is in frontend just a frame shows that the page is recaptcha protected, and the recaptcha is not showing in div tag?
what is the solution?
I didn't receive any error
`  showRegsitrationForm(req , res) {
        res.render('register' , { messages : req.flash('errors') , recaptcha : this.recaptcha.render() });
    }`

`recaptchaConfig(){
      
        this.recaptcha = new Recaptcha(
            '!!!',
            '!!!' , 
          {callback:'cb'},{'hl' : 'en'}
        );
    }
`

**Comment by pdupavillon** [comment]
@vahid263 are you still having the problem?
Another version has been released the same day you create that issue.
