### ISSUE TITLE
Is app.use(bodyParser.json()) a real requirement ?

### ISSUE THREAD

**Issue by sylbal** [pdupavillon/express-recaptcha#46]
Hi,

Our implementation seems to be functional without the `app.use(bodyParser.json());` line (that we missed by error). Is it a real requirement for most implementations and we have an easy-lucky use case ?

Regards

**Comment by tpwatson** [comment]
Check your Express version. The Readme file says:
Body Parser is only a requirement "If you're using an express version older than 4.16.0"
