### ISSUE TITLE
body-parser needed

### ISSUE THREAD

**Issue by lacksfish** [pdupavillon/express-recaptcha#6]
First of all, thank you a lot for this package!

Now, I was trying to use it and at first, didn't get it to run
https://stackoverflow.com/a/12008719
This is the solution that worked for me. There's differences between express 2, 3 and 4, especially regarding how POST params are parsed. Well, works now. :)

**Comment by pdupavillon** [comment]
Hi @lacksfish,
Thanks for this feedback, I'll add it to the readme file.
