### ISSUE TITLE
body-parser

### ISSUE THREAD

**Issue by Moofx** [pdupavillon/express-recaptcha#7]
For funkcionality is needed **body-parser** npm package. Because there are handled **post** requests.
I dont know why that information missing in readme. And on the other hand why is there present settings for public directory that is unrelated with such captcha feature.
It would be helpfull especialy for node noobies add such information. But I understand that everyone love keeping their modules without any additional dependency. And who knows maybe body-parser is de facto standard in node world. But anyway posted so maybe someone find help here.

**Comment by pdupavillon** [comment]
duplicate with issue #6
